### ISSUE TITLE
Allow file download or opening rich content in other apps

### ISSUE THREAD

**Issue by s-ol** [OnionBrowser/OnionBrowser#10] opened 2012-05-11 20:26 UTC
Hi there!
Good work in The Browser! i'd love to take my PDFs and stuff with me. If you dont want/cant add a filemanager, an "open in..." button would be nice.

**Comment by ikonkere** [comment] 2018-03-13 06:54
Any progress on this one? This is the most important feature for users who use Tor to download stuff that is otherwise unavailable in their country.

**Comment by Baccount** [comment] 2018-03-13 07:04
I would also like this feature. @mtigas

**Comment by tladesignz** [comment] 2019-04-03 16:37
@mtigas: I had a first shot at an implementation, or better, an extension to the "Share URL" feature. (See referenced commit above.)

Currently, I have 2 issues:

1. How do I access the raw `NSData` of the `UIWebView`? It seems impossible. There is a feature to hack into the page with JavaScript, but that doesn't give me the raw PDF, just a made-up mini-markup embedding the PDF.

2. If there's no possibility to directly grab the PDF (or other documents, images, etc.) from `UIWebView`, I need to re-download it. How do I hook up `NSURLSession` to Tor? My first tries circumvented that.

3. Or can we somehow make stuff like that available from `URLInterceptor`? How to design that? We need to talk... @DavidMOliver, turns out, I need @mtigas - he's written some of the important code there!

**Comment by tladesignz** [comment] 2019-05-03 09:31
Just checked, how image saving is implemented:

https://github.com/OnionBrowser/OnionBrowser/blob/dfac7d8a38d1fc158a88e7da35669e32c4836d97/Endless/WebViewTab.m#L793

```Objective-C
NSData *imgdata = [NSData dataWithContentsOfURL:imgurl];
```

That has 3 issues:

1. It needs to re-load the image, although `UIWebView` already did that.
2. It loads *synchronously*. With images, that's normally not much of a problem, but still not good.
3. The HTTP user-agent header is set to "OnionBrowser/91998.491966232 CFNetwork/978.0.7 Darwin/18.5.0".

**BUT** it uses the Tor network, so that's ok, compared to `NSURLSession.dataTaskWithURL` which bypasses it.

**Comment by tladesignz** [comment] 2019-12-13 12:32
This is actually now implemented/fixed with all the rework done lately. Most files like images, pdfs and the like should now (or in the next release) be easily shareable into other apps.

**Comment by ikonkere** [comment] 2019-12-13 13:20
It doesn't work for me yet (using 2.2.1 available in iOS AppStore).

Reproduce: paste this url http://flibustahezeous3.onion/b/151260/epub to Onion Browser search bar.

Expected: an EPUB file named `Lukyanenko_Genom_1_Genom.151260.fb2.epub` should download (as it does in Tor browser desktop) and a choice is offered to save it to iOS Files app or open it in Books app (or whatever is the default behaviour in e.g. Safari mobile when downloading files).

Observed: literally nothing happens.

**Comment by tladesignz** [comment] 2019-12-13 13:31
Argh. Yeah, I'm sorry. No new release, yet. 
I tested your provided link and can confirm it will work with the next release, though! 
Please be patient, there's a release upcomming until end of year. 
Or maybe beginning of next, depending on Apple. :-)

**Comment by ikonkere** [comment] 2019-12-13 13:43
Ah, i suspected as much seeing `2.4.0` fix tag in milestones. Can't wait for the new release, thanks for great work! Even though it only took 8 years to implement ;).

**Comment by tladesignz** [comment] 2019-12-18 12:16
> Ah, i suspected as much seeing `2.4.0` fix tag in milestones. Can't wait for the new release, thanks for great work! Even though it only took 8 years to implement ;).

Not really. It took 8 years to gather enough money and code we're relying on.

This app cost north of 1 million US$ if you're counting in all the dependencies esp. Tor. (not iOS, of course) And even without Tor it would probably be more than 250k.

**Comment by ikonkere** [comment] 2020-01-13 10:15
Worth mentioning that 2.4.0 brought a regression to this functionality from 2.3.0 (iOS 13). Clicking on download links result in two distinct behaviour patterns:
1) Accessing the link mentioned above (http://flibustahezeous3.onion/b/151260/epub) produces this screen:
![Untitled4](https://user-images.githubusercontent.com/11472129/72247265-91f96b00-3605-11ea-9074-e177ee5a781d.png)
Bottom navigation bar disappears without any way to bring it back (so you can't even access settings, or go back in browsing history, and the only way to use the browser further is to kill it and start anew) while the download doesn't do anything (no sharing, no anything).

2) Sometimes (i couldn't determine the right way to reproduce it) the bottom navigation bar remains, but no sharing to Books.app is available
![Untitled2](https://user-images.githubusercontent.com/11472129/72247482-06cca500-3606-11ea-821f-a97b7a89be08.png)
unless i use "Save to files" and save the file to Dropbox or phone local storage and then import to Books.app.

I tested this functionality when 2.3.0 was released and it definitely worked as intended.

**Comment by ikonkere** [comment] 2020-01-14 15:52
Ah, i think i got it. Navigation bar disappears if you clicked on a download link having pinch-zoomed onto the web-page prior to clicking on the link.

**Comment by tladesignz** [comment] 2020-01-16 21:03
Thanks a lot for catching this!

**Comment by tladesignz** [comment] 2020-01-17 14:56
Hurray to Apple's documentation! Next release should have this all fixed. Thanks a lot, again!

**Closed by tladesignz** 2020-01-17 14:56 UTC
Labels: enhancement

**Comment by m4mb01t4l14n0** [comment] 2020-01-17 15:09
YAY!

**Comment by ikonkere** [comment] 2020-03-10 16:53
Can confirm it works in 2.5.0, great job!
